"""
Manages master FFmpeg processes for HLS streaming.
Depends on stream_tracker.py to record stream information.
"""
import os
import subprocess
import time # Added to resolve NameError for time.sleep()
import stream_tracker # Assumes stream_tracker.py is in the same directory or PYTHONPATH
import shutil # For cleanup in start_master_stream if add_stream fails

# Configuration Constants
HLS_BASE_PATH = "/mnt/hls_streams"
FFMPEG_COMMAND = "ffmpeg"  # Assumes ffmpeg is in PATH
HLS_SEGMENT_DURATION = 10
HLS_LIST_SIZE = 6
# Placeholder for a command/script that handles stream failover.
# E.g., "python /path/to/failover_handler.py" or "my_stream_wrapper"
# If empty, FFmpeg will directly use the original_url.
# If set, it's assumed this script takes the original_url as an argument
# and pipes a reliable stream to stdout, which FFmpeg will then read via pipe:0.
FAILOVER_WRAPPER_COMMAND = ""


def start_master_stream(original_url: str, channel_id: str) -> str | None:
    """
    Starts a master FFmpeg process for HLS streaming.

    Args:
        original_url: The URL of the source video stream.
        channel_id: The unique ID for this channel (e.g., generated by stream_tracker.generate_channel_id).

    Returns:
        The path to the HLS playlist (.m3u8) file on success, or None on failure.
    """
    hls_output_path = os.path.join(HLS_BASE_PATH, channel_id)
    hls_playlist_file = os.path.join(hls_output_path, "playlist.m3u8")
    ffmpeg_log_file = os.path.join(hls_output_path, "ffmpeg.log")

    # Create HLS output directory
    try:
        os.makedirs(hls_output_path, exist_ok=True)
        print(f"Ensured HLS output directory exists: {hls_output_path}")
    except OSError as e:
        print(f"Error creating HLS directory {hls_output_path}: {e}")
        return None

    # Construct FFmpeg command
    ffmpeg_cmd_args = [
        FFMPEG_COMMAND,
        '-hide_banner', # Optional: cleans up FFmpeg console output
        '-loglevel', 'error', # Optional: reduces FFmpeg verbosity in logs, adjust as needed
    ]

    input_options = []
    ffmpeg_process_stdin = None
    failover_process = None # Keep track of the failover process

    if FAILOVER_WRAPPER_COMMAND:
        print(f"Using FAILOVER_WRAPPER_COMMAND: '{FAILOVER_WRAPPER_COMMAND}' for URL: {original_url}")
        # Prepare the failover command. It's crucial this command is well-behaved.
        # Using shell=False is safer, so FAILOVER_WRAPPER_COMMAND should be a list if it has args,
        # or we split it. For simplicity, assuming it's a simple command or path to script.
        # If FAILOVER_WRAPPER_COMMAND can have arguments, it should be a list.
        # For this example, we'll assume it's a string that might need splitting if it's complex.
        # A better approach is to define FAILOVER_WRAPPER_COMMAND as a list of arguments.
        # e.g., FAILOVER_WRAPPER_COMMAND = ["python", "/path/to/script.py"]
        wrapper_cmd_args = FAILOVER_WRAPPER_COMMAND.split() + [original_url]
        try:
            failover_log_file = os.path.join(hls_output_path, "failover_wrapper.log")
            with open(failover_log_file, 'wb') as failover_log_fp:
                failover_process = subprocess.Popen(
                    wrapper_cmd_args,
                    stdout=subprocess.PIPE,
                    stderr=failover_log_fp, # Log stderr of wrapper
                    start_new_session=True # Detach wrapper as well, or manage as part of FFmpeg's lifecycle
                )
            print(f"Failover wrapper process started with PID: {failover_process.pid}. Logging to: {failover_log_file}")
            ffmpeg_process_stdin = failover_process.stdout
            input_options.extend(['-re', '-i', 'pipe:0']) # -re is often needed for reading from pipe at native frame rate
        except (subprocess.SubprocessError, FileNotFoundError) as e:
            print(f"Error starting failover wrapper command '{FAILOVER_WRAPPER_COMMAND}': {e}")
            if os.path.exists(hls_output_path): # Cleanup HLS dir
                shutil.rmtree(hls_output_path)
                print(f"Cleaned up HLS directory due to failover wrapper start failure: {hls_output_path}")
            return None
    else:
        # Direct input, no failover wrapper
        input_options.extend(['-i', original_url])

    ffmpeg_cmd_args.extend(input_options)

    # HLS output options
    ffmpeg_cmd_args.extend([
        '-c:v', 'copy',
        '-c:a', 'copy',
        '-f', 'hls',
        '-hls_time', str(HLS_SEGMENT_DURATION),
        '-hls_list_size', str(HLS_LIST_SIZE),
        '-hls_flags', 'delete_segments',
        '-hls_segment_filename', os.path.join(hls_output_path, "segment%03d.ts"),
        hls_playlist_file
    ])

    print(f"Constructed FFmpeg command: {' '.join(ffmpeg_cmd_args)}")

    # Launch FFmpeg
    ffmpeg_pid = None
    
    # Prepare FFREPORT environment variable for FFmpeg
    # ffmpeg_log_file path is already defined: os.path.join(hls_output_path, "ffmpeg.log")
    # Ensure the log path uses forward slashes for FFREPORT, especially on Windows, though FFmpeg might handle it.
    # For safety, explicitly convert. Python's os.path.join behaves correctly for the OS.
    # FFmpeg's FFREPORT path interpretation is usually flexible.
    ffreport_val = f"file={ffmpeg_log_file.replace(os.path.sep, '/')}:level=32" # level 32 is INFO
    current_env = os.environ.copy()
    current_env["FFREPORT"] = ffreport_val
    
    print(f"Setting FFREPORT for FFmpeg: {ffreport_val}")

    try:
        process = subprocess.Popen(
            ffmpeg_cmd_args,
            stdin=ffmpeg_process_stdin, # Handles input from wrapper if implemented
            # stdout and stderr are not redirected to Python; FFmpeg handles logging via FFREPORT
            # For true detachment without Python holding pipes, one might use:
            # stdout=subprocess.DEVNULL, 
            # stderr=subprocess.DEVNULL,
            # However, FFREPORT handles logging, so default behavior (inheritance or DEVNULL based on context) is fine.
            # Removing explicit stdout/stderr redirection is the key change.
            start_new_session=True, # Detach from parent
            env=current_env # Pass the modified environment with FFREPORT
        )
        ffmpeg_pid = process.pid
        # Note: The log message now refers to the log file FFmpeg itself is creating.
        print(f"FFmpeg process started with PID: {ffmpeg_pid} for channel: {channel_id}. FFmpeg internal logging to: {ffmpeg_log_file}")

        # Give FFmpeg a moment to start and potentially fail fast
        time.sleep(2) # Small delay
        if process.poll() is not None: # Process has terminated
            if failover_process:
                print(f"FFmpeg terminated early. Terminating failover wrapper process PID: {failover_process.pid}")
                failover_process.terminate()
                try:
                    failover_process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    print(f"Failover wrapper {failover_process.pid} did not terminate gracefully, killing.")
                    failover_process.kill()
            # Include FFREPORT path in error, as FFmpeg is managing this log.
            raise RuntimeError(f"FFmpeg process {ffmpeg_pid} terminated unexpectedly shortly after start. Check FFmpeg's own log at {ffmpeg_log_file}.")

    except (subprocess.SubprocessError, FileNotFoundError, RuntimeError) as e:
        print(f"Error starting FFmpeg for {original_url} (channel: {channel_id}): {e}")
        if failover_process: # If failover process was started, ensure it's cleaned up
            print(f"Cleaning up failover_process PID {failover_process.pid} due to FFmpeg start error.")
            failover_process.terminate()
            try:
                failover_process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                failover_process.kill()
        if os.path.exists(hls_output_path): # Cleanup HLS dir
            shutil.rmtree(hls_output_path)
            print(f"Cleaned up HLS directory due to FFmpeg start failure: {hls_output_path}")
        return None

    # Add stream to tracker
    if ffmpeg_pid:
        # Store failover_pid if present. This is a simple way.
        # A more structured way would be to have a dedicated field in Redis.
        # For now, we can pass it as part of original_url or a new field if stream_tracker is adapted.
        # Let's assume for now stream_tracker.add_stream is not changed.
        # The PID of the failover wrapper (if any) needs to be managed for proper cleanup when stopping streams.
        # This example focuses on starting; stopping would need to retrieve this info.
        # One option: stream_tracker.add_stream(..., failover_pid=failover_process.pid if failover_process else None)
        # This requires changing stream_tracker. For now, we only store ffmpeg_pid.
        if stream_tracker.add_stream(channel_id, original_url, ffmpeg_pid, hls_playlist_file):
            print(f"Stream {channel_id} (FFmpeg PID: {ffmpeg_pid}) added to tracker successfully.")
            if failover_process:
                print(f"Associated Failover Wrapper PID: {failover_process.pid}")
            return hls_playlist_file
        else:
            print(f"Failed to add stream {channel_id} to tracker (it might already exist or Redis error).")
            # Terminate the newly started FFmpeg process
            print(f"Terminating FFmpeg process PID: {ffmpeg_pid} due to stream_tracker failure.")
            try:
                # process.terminate() / process.kill() would be better if 'process' object is kept
                subprocess.run(["kill", str(ffmpeg_pid)], check=False) # SIGTERM
                time.sleep(1)
                kill_check = subprocess.run(["kill", "-0", str(ffmpeg_pid)], capture_output=True, text=True)
                if kill_check.returncode == 0:
                    print(f"FFmpeg process {ffmpeg_pid} still alive, sending SIGKILL.")
                    subprocess.run(["kill", "-9", str(ffmpeg_pid)], check=False)
            except ProcessLookupError:
                print(f"FFmpeg process {ffmpeg_pid} not found for termination (already exited?).")
            except Exception as e_kill:
                print(f"Error terminating FFmpeg process {ffmpeg_pid}: {e_kill}")

            # Terminate the failover process if it exists
            if failover_process:
                print(f"Terminating failover wrapper process PID: {failover_process.pid} due to stream_tracker failure.")
                failover_process.terminate()
                try:
                    failover_process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    print(f"Failover wrapper {failover_process.pid} did not terminate gracefully, killing.")
                    failover_process.kill()
            
            # Clean up HLS directory
            if os.path.exists(hls_output_path):
                shutil.rmtree(hls_output_path)
                print(f"Cleaned up HLS directory: {hls_output_path}")
            return None
    else:
        # This case should ideally be caught by the exception block above.
        print("FFmpeg PID not obtained, cannot add to tracker.")
        # Ensure failover process is cleaned up if it exists and FFmpeg PID was not obtained for other reasons.
        if failover_process:
            print(f"Cleaning up failover_process PID {failover_process.pid} as FFmpeg PID was not obtained.")
            failover_process.terminate()
            try:
                failover_process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                failover_process.kill()
        return None


if __name__ == '__main__':
    # This block serves as a basic integration test for ffmpeg_manager.
    # It requires:
    # 1. FFmpeg installed and in PATH.
    # 2. Redis server running and accessible.
    # 3. stream_tracker.py in the same directory or PYTHONPATH.
    # 4. Write permissions to HLS_BASE_PATH.

    print("\n--- FFmpeg Manager Test Suite ---")

    # Ensure Redis connection via stream_tracker
    if not stream_tracker._get_redis_connection():
        print("CRITICAL: Failed to connect to Redis via stream_tracker. Aborting ffmpeg_manager tests.")
        exit(1)
    print("Successfully connected to Redis for testing.")

    # Test Data
    # Using a known public HLS stream that FFmpeg can process.
    # If this URL becomes invalid, tests may fail.
    valid_test_url = "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8"
    valid_channel_id = stream_tracker.generate_channel_id(valid_test_url)
    
    error_test_url = "http://thisshouldnotexist.invalid/stream.m3u8"
    error_channel_id = stream_tracker.generate_channel_id(error_test_url)

    def cleanup_test_stream_resources(channel_id_to_clean):
        """Helper function to clean up resources for a given channel_id."""
        print(f"\n--- Test Cleanup for Channel ID: {channel_id_to_clean} ---")
        stream_info = stream_tracker.get_stream(channel_id_to_clean)
        if stream_info and 'pid' in stream_info:
            pid = stream_info['pid']
            print(f"Attempting to stop FFmpeg process PID: {pid} for channel {channel_id_to_clean}.")
            try:
                # Send SIGTERM first for graceful shutdown
                subprocess.run(["kill", str(pid)], check=False, timeout=5)
                time.sleep(2) # Give it a moment to terminate
                # Check if still alive, then send SIGKILL
                kill_check_result = subprocess.run(["kill", "-0", str(pid)], capture_output=True, text=True)
                if kill_check_result.returncode == 0:
                    print(f"FFmpeg process {pid} still alive after SIGTERM, sending SIGKILL.")
                    subprocess.run(["kill", "-9", str(pid)], check=False, timeout=5)
                print(f"Kill signals sent for FFmpeg process PID: {pid}.")
            except ProcessLookupError:
                print(f"FFmpeg process PID: {pid} not found (already terminated).")
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e_kill:
                print(f"Error during FFmpeg process termination for PID {pid}: {e_kill}")
            except Exception as e_generic_kill: # Catch any other unexpected error during kill
                print(f"A generic error occurred during FFmpeg process termination for PID {pid}: {e_generic_kill}")
        
        # Remove from Redis using stream_tracker
        if stream_tracker.remove_stream(channel_id_to_clean):
            print(f"Stream {channel_id_to_clean} removed from tracker.")
        else:
            print(f"Stream {channel_id_to_clean} not found in tracker or failed to remove.")

        # Remove HLS directory from filesystem
        hls_directory = os.path.join(HLS_BASE_PATH, channel_id_to_clean)
        if os.path.exists(hls_directory):
            try:
                shutil.rmtree(hls_directory)
                print(f"HLS directory {hls_directory} removed.")
            except OSError as e_rm:
                print(f"Error removing HLS directory {hls_directory}: {e_rm}")
        else:
            print(f"HLS directory {hls_directory} not found, no removal needed.")
        print(f"--- Test Cleanup for Channel ID: {channel_id_to_clean} Complete ---")

    # --- Test Case 1: Start a new valid stream ---
    print(f"\n--- Test Case 1: Starting a new valid stream ---")
    print(f"URL: {valid_test_url}, Channel ID: {valid_channel_id}")
    # Perform pre-test cleanup for the valid_channel_id
    cleanup_test_stream_resources(valid_channel_id)
    
    print(f"Attempting to start master stream...")
    playlist_path = start_master_stream(valid_test_url, valid_channel_id)

    if playlist_path:
        print(f"SUCCESS: start_master_stream returned playlist path: {playlist_path}")
        assert os.path.exists(playlist_path), f"Playlist file {playlist_path} does not exist on filesystem."
        print(f"Verified playlist file exists at: {playlist_path}")

        stream_info_from_tracker = stream_tracker.get_stream(valid_channel_id)
        assert stream_info_from_tracker is not None, f"Stream {valid_channel_id} not found in tracker after start."
        assert stream_info_from_tracker['pid'] is not None, "PID not stored in tracker."
        print(f"Stream info from tracker: {stream_info_from_tracker}")
        ffmpeg_pid = stream_info_from_tracker['pid']
        print(f"FFmpeg PID: {ffmpeg_pid}. Verifying process is running...")
        
        # Verify FFmpeg process is actually running
        try:
            os.kill(ffmpeg_pid, 0) # Check if process exists
            print(f"SUCCESS: FFmpeg process PID {ffmpeg_pid} is running.")
        except ProcessLookupError:
            print(f"FAILURE: FFmpeg process PID {ffmpeg_pid} not found after start_master_stream indicated success.")
            assert False, "FFmpeg process not running after supposedly successful start."
        except PermissionError:
            print(f"WARNING: Cannot verify FFmpeg PID {ffmpeg_pid} due to permissions, but stream was registered.")

        # Wait for a short period to allow FFmpeg to generate some segments.
        # Note: 15 seconds is a long time for a unit/integration test.
        # Consider reducing or making this check optional / more robust if time is critical.
        print(f"Waiting for 10 seconds to check for HLS segment files...")
        time.sleep(10) 
        hls_output_dir = os.path.join(HLS_BASE_PATH, valid_channel_id)
        segment_files = [f for f in os.listdir(hls_output_dir) if f.startswith("segment") and f.endswith(".ts")]
        if segment_files:
            print(f"SUCCESS: Found {len(segment_files)} segment file(s) in {hls_output_dir} (e.g., {segment_files[0]}).")
        else:
            print(f"WARNING: No segment files found in {hls_output_dir} after 10s. FFmpeg might have issues with the source or writing.")
            # This is not an assert False because network or source issues can cause this.
            # The core test is that start_master_stream succeeded and the process was running.
        
        # Log file check
        ffmpeg_log_path = os.path.join(hls_output_dir, "ffmpeg.log")
        assert os.path.exists(ffmpeg_log_path), f"FFmpeg log file {ffmpeg_log_path} not found."
        print(f"FFmpeg log file found at {ffmpeg_log_path}.")

    else:
        print(f"FAILURE: start_master_stream failed for valid URL: {valid_test_url}")
        # Check if log file was created even on failure (it should be if directory creation succeeded)
        hls_output_dir = os.path.join(HLS_BASE_PATH, valid_channel_id)
        ffmpeg_log_path = os.path.join(hls_output_dir, "ffmpeg.log")
        if os.path.exists(ffmpeg_log_path):
             print(f"FFmpeg log file found at {ffmpeg_log_path}. Please inspect for error details.")
        assert False, "start_master_stream failed for a known valid URL."

    # Perform post-test cleanup for the valid_channel_id
    cleanup_test_stream_resources(valid_channel_id)

    # --- Test Case 2: Attempting to start a stream with a non-existent/error URL ---
    print(f"\n--- Test Case 2: Starting a stream with an invalid URL ---")
    print(f"URL: {error_test_url}, Channel ID: {error_channel_id}")
    # Perform pre-test cleanup for the error_channel_id
    cleanup_test_stream_resources(error_channel_id)

    print(f"Attempting to start master stream with invalid URL...")
    error_playlist_path = start_master_stream(error_test_url, error_channel_id)

    assert error_playlist_path is None, "start_master_stream should have returned None for an invalid URL."
    print(f"SUCCESS: start_master_stream correctly returned None for the invalid URL.")
    
    # Verify that no stream entry was created in Redis
    assert stream_tracker.get_stream(error_channel_id) is None, f"Stream {error_channel_id} found in tracker despite failed start."
    print(f"Verified that stream {error_channel_id} is not in tracker.")

    # Verify that the HLS directory (if created) was cleaned up, or specific log file exists
    hls_error_dir = os.path.join(HLS_BASE_PATH, error_channel_id)
    ffmpeg_error_log_path = os.path.join(hls_error_dir, "ffmpeg.log")
    if os.path.exists(hls_error_dir):
        # If the directory exists, it implies FFmpeg might have tried to start.
        # The start_master_stream function should clean this up if it fails.
        # However, if the failure is very early (e.g., directory creation itself), it might not exist.
        # If it does exist, the log should be there.
        assert os.path.exists(ffmpeg_error_log_path), f"ffmpeg.log not found in {hls_error_dir} after failed start."
        print(f"FFmpeg log for failed stream found at {ffmpeg_error_log_path}. Inspect for details.")
        # Assert that the directory IS cleaned up by start_master_stream on failure
        # This depends on the stage of failure. If Popen fails, dir is cleaned.
        # If Popen succeeds but ffmpeg exits quickly, dir is also cleaned.
        # The check here confirms if a log was made, implying the dir was made.
        # The cleanup_test_stream_resources will ensure it's gone after this test regardless.
    else:
        print(f"HLS directory {hls_error_dir} was correctly not found or cleaned up after failed start.")
        
    # Perform post-test cleanup for the error_channel_id
    cleanup_test_stream_resources(error_channel_id)
    
    print("\n--- FFmpeg Manager Test Suite Complete ---")

# Note on FAILOVER_WRAPPER_COMMAND:
# Testing the FAILOVER_WRAPPER_COMMAND functionality within this __main__ block is complex
# as it requires a specific, executable wrapper script to be available and configured.
# The current tests focus on the direct URL input scenario, which is the primary path
# when FAILOVER_WRAPPER_COMMAND is empty. Manual testing (see TESTING_PLAN.md)
# would be more appropriate for the failover wrapper scenario.
#
# Note on FFmpeg Dependency:
# These tests will fail if FFmpeg is not installed or not in the system PATH.
# They involve real process execution and filesystem interaction.
#
# Note on HLS_BASE_PATH:
# Ensure HLS_BASE_PATH is writable by the user running this script.
# The default /mnt/hls_streams might require sudo or permissions adjustments.
# For automated testing in CI, this path should be configurable or use a temp directory.

# (Existing comments from original file, slightly re-ordered to fit context)
# The `start_new_session=True` is for detaching FFmpeg. If a wrapper is used,
# the wrapper might also need careful process management.
# The `time.sleep(2)` after Popen and `process.poll()` check is a basic check for immediate FFmpeg errors.
# More robust solutions like `process.wait(timeout=X)` in a try-except or monitoring playlist creation exist.
# The current approach covers the primary requirements.
# The cleanup in the main test block also tries to kill processes, which might need sudo
# or specific permissions depending on the environment where this is run.
# The test for playlist and segment creation is a good indicator of success.
# In a real system, a monitoring thread/process would periodically check FFmpeg health.
# Added a specific check for FFmpeg termination after start.
# Ensured cleanup of HLS directory on stream_tracker.add_stream failure and FFmpeg start failure.
# Refined process termination logic.
# Added -hide_banner and -loglevel error to ffmpeg command for cleaner logs.
# Kept HLS directory for main test for inspection (though cleanup function now removes it).
# Added check for ProcessLookupError during cleanup.
# The `FAILOVER_WRAPPER_COMMAND` logic is more fully implemented now but tested manually.
# Added `RuntimeError` for FFmpeg immediate exit.
# Made `HLS_BASE_PATH` an absolute path as intended.
# Corrected the cleanup logic when `stream_tracker.add_stream` fails.
# It should now correctly attempt to kill the PID and failover_process if any.
# Added `start_new_session=True` to `subprocess.Popen` to ensure FFmpeg runs detached.
# Added `shutil` to imports.
# Added `import time` to module level.
# Added `ffmpeg_process_stdin` for the `FAILOVER_WRAPPER_COMMAND` case.
# Added more robust cleanup in the main test, attempting SIGTERM then SIGKILL.
