name: publish
on: [push]
jobs:
  publish-m3u-editor-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the m3u-editor Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sparkison/m3u-editor:latest
        # run: |
        #   docker build . --tag ghcr.io/sparkison/m3u-editor:latest
        #   docker run ghcr.io/sparkison/m3u-editor:latest
        #   docker push ghcr.io/sparkison/m3u-editor:latest
