name: Dev
on:
  push:
    branches: [dev]

jobs:
  push-amd64:
    name: Publish dev m3u-editor Docker image (amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push amd64
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: sparkison/m3u-editor:dev-amd64
          provenance: false
          sbom: false

  push-arm64:
    name: Publish dev m3u-editor Docker image (arm64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push arm64
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          push: true
          tags: sparkison/m3u-editor:dev-arm64
          provenance: false
          sbom: false

  push-manifest:
    name: Push Docker Manifest for dev
    runs-on: ubuntu-latest
    needs: [push-amd64, push-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest list
        run: |
          docker manifest create sparkison/m3u-editor:dev \
            sparkison/m3u-editor:dev-amd64 \
            sparkison/m3u-editor:dev-arm64
      
      - name: Push manifest list
        run: docker manifest push sparkison/m3u-editor:dev